// Settings
:idprefix:
:idseparator: -
:page-component-title: Application de génération d’une base de données relationnelle à partir d’une ontologie
:page-component-name: Ontorela
= {page-component-name}

[#summary]
== Sommaire
*{page-component-name}* génère à partir d'une ontologie et des critères de modélisation, à la fois un ensemble de scripts qui créent une base de données relationnelle (BDR) entièrement fonctionnelle et des graphes de propriétés.

SGBDs actuellement pris en charge:

* Relationnel: PostgreSQL
* Graphe: Neo4j & AgensGraph

[#techno]
== Technologies utilisées
L' *{page-component-name}* est développée en Java et utilise Gradle comme outil de construction automatisée
(« build automation tools »).

Les libraires externes suivantes ont été utilisées:

* [OWLAPI](https://github.com/owlcs/owlapi)
* [SnakeYAML](https://github.com/snakeyaml/snakeyaml)
* [JGraphT](https://jgrapht.org)
* [JUnit Jupiter](https://junit.org)
* [StringTemplate](https://www.stringtemplate.org)

Le fichier exécutable sera dans le répertoire `build/libs`.

=== Entrées

Le logiciel prend en entrée deux fichiers de configuration :

* [nom-de-l'ontologie]-database_config.yaml : contenant les paramètres nécessaires à la création de la base de données relationnelle
* [nom-de-l'ontologie]-ontology_config.yaml : contenant les paramètres nécessaires à la lecture des composants ontologiques

=== Sorties

Le logiciel génère, à partir d'une ontologie, un ensemble de scripts Cypher qui permettent de construire des graphes de propriétés compatibles avec Neo4j et AgensGraph.

=== Utilisation client pour génération des scripts Cypher

Les pré-requis :

* Java 17+
* AgensGraph v2.14.1+ ou
* Neo4j Desktop v2.1.4+

Les étapes :

. Clôner le dépôt.
. Dans le terminal exécuter : +
----
 java -jar build/libs/ontorela-application-2.3.0-SNAPSHOT.jar generate-cypher <configuration_directory>
----

== Équipe

Pour plus d'information contacter: +
Christina Khnaisser : Christina.Khnaisser@usherbrooke.ca

Collaborateurs.trices : +
Reine Sonkin Fozi : Reine.Sonkin.Fozi@usherbrooke.ca

Merci à : +
Ameni Souid :  Ameni.Souid@USherbrooke.ca +
Mohamed Amin Gaied :  Mohamed.Amin.Gaied@USherbrooke.ca +
Mouhamad Moustapha Mbaye : Mouhamad.Moustapha.Mbaye@USherbrooke.ca

== Références
Khnaisser, Chantal, Luc Lavoie, Benoit Fraikin, Alan Barton, Sébastien Dussault, Anita Burgun, et Jean-François Ethier. « Using an ontology to derive a sharable and interoperable relational data model for heterogeneous healthcare data and various applications ». In Methods of Information in Medicine, 61(S 02):e73–e88, (Jun 2022). https://doi.org/10.1055/a-1877-9498.

[#licence]
== Copyright et licences

=== Copyright
include::copyright.adoc[]

=== Licences
Le code de ce projet est sous licence
link:liliqr-licence.adoc[LILIQ-R].

La documentation de ce projet est sous licence
https://creativecommons.org/licenses/by/4.0/[CC BY 4.0].
