// Settings
:idprefix:
:idseparator: -
:page-component-title: Application de génération de bases de données à partir d’une ontologie
:page-component-name: OntoRel-App
= {page-component-name}

[#summary]
== Sommaire
*{page-component-name}* génère à partir d'une ontologie et des critères de modélisation, 
un ensemble de scripts pour la création d'une base de données relationnelle et des bases de données de graphes.

SGBDs actuellement pris en charge:

* Relationnel: 
** PostgreSQL
* Graphe: 
** Neo4j 
** AgensGraph

[#techno]
== Technologies utilisées
L' *{page-component-name}* est développée en Java et utilise Gradle comme outil de construction automatisée
(« build automation tools »).

Les libraires externes suivantes ont été utilisées:

* https://github.com/owlcs/owlapi[OWLAPI]
* https://github.com/snakeyaml/snakeyaml[SnakeYAML]
* https://jgrapht.org[JGraphT]
* https://junit.org[JUnit Jupiter]
* https://www.stringtemplate.org[StringTemplate]

Le fichier exécutable est dans le répertoire `build/libs`.

=== Entrées

`{page-component-name}` prend en entrée deux fichiers de configuration :

* [nom-de-l'ontologie]-database_config.yaml : contenant les paramètres nécessaires à la création de la base de données relationnelle.
* [nom-de-l'ontologie]-ontology_config.yaml : contenant les paramètres nécessaires à la lecture des composants ontologiques.

=== Sorties

`{page-component-name}` génère :

* l'ontologie normalisée;
* les scripts de la base de données relationnelle;
* une liste des anomalies trouvées dans l'ontologie;
* un catalogue de mise en correspondance entre des constructeurs ontologiques et les constructeurs relationnels (OntoRelCat).
* le graphe :
** de l'ontologie normalisée (OntoGraph);
** du schéma relationnel (RelGraph);
** du schéma ontologique-relationnel (OntoRelGraph).

== Utilisation client 

Les pré-requis :

* Java 17+

=== Génération des scripts Cypher

Les pré-requis :

* Neo4j Desktop 2.x ou
* AgensGraph Community Edition v2.x

Les étapes :

. Clônez le dépôt.
. xref:demo/lisezmoi.adoc#demos[Créez vos propres fichiers de configuration] ou réutilisez n'importe quel ensemble de fichiers de configuration présent dans le dossier `/demo`.
. Dans le terminal, depuis le répertoire racine du projet, exécutez la commande suivante : +
----
 java -jar build/libs/ontorela-application-2.3.0-SNAPSHOT.jar generate-cypher <configuration_directory>
----

Suivez xref:demo/lisezmoi.adoc#utilisation[ces étapes] pour exécuter les démonstrations.

== Équipe

Pour plus d'information contacter: +
Christina Khnaisser : Christina.Khnaisser@usherbrooke.ca

Collaborateurs.trices : +
Reine Sonkin Fozi : Reine.Sonkin.Fozi@usherbrooke.ca +
Ameni Souid :  Ameni.Souid@USherbrooke.ca +
Mohamed Amin Gaied :  Mohamed.Amin.Gaied@USherbrooke.ca +
Mouhamad Moustapha Mbaye : Mouhamad.Moustapha.Mbaye@USherbrooke.ca

== Références
Khnaisser, C., Looten, V., Lavoie, L., Burgun, A., & Ethier, J.-F. (2024). Building ontology-based temporal databases for data reuse: An applied example on hospital organizational structures. Health Informatics Journal, 30(2). https://doi.org/10.1177/14604582241259336

Khnaisser, C., Lavoie, L., Fraikin, B., Barton, A., Dussault, S., Burgun, A., & Ethier, J.-F. (2022). Using an ontology to derive a sharable and interoperable relational data model for heterogeneous healthcare data and various applications. Methods of Information in Medicine, a–1877–9498. https://doi.org/10.1055/a-1877-9498

Khnaisser, C. (2019). Construction de modèles de données relationnels temporalisés guidée par les ontologies [PhD thesis, Université de Paris cotutelle Université de Sherbrooke]. https://theses.fr/273756915

Khnaisser, C., Lavoie, L., Burgun, A., & Ethier, J.-F. (2018). Generating Relational Database using Ontology Review : Issues, Challenges and Trends. International Journal of Advanced Computer Science and Applications (IJACSA), 9(6), 139–145. https://doi.org/10.14569/IJACSA.2018.090620

Khnaisser, C., Lavoie, L., Diab, H., & Ethier, J.-F. (2015). Data Warehouse Design Methods Review: Trends, Challenges and Future Directions for the Healthcare Domain. In T. Morzy, P. Valduriez, & L. Bellatreche (Eds.), New Trends in Databases and Information Systems. ADBIS 2015. Communications in Computer and Information Science (Issue 539, pp. 76–87). Springer International Publishing. http://link.springer.com/chapter/10.1007/978-3-319-23201-0_10

[#licence]
== Copyright et licences

=== Copyright
include::copyright.adoc[]

=== Licences
Le code de ce projet est sous licence
link:liliqr-licence.adoc[LILIQ-R].

La documentation de ce projet est sous licence
https://creativecommons.org/licenses/by/4.0/[CC BY 4.0].
