// Settings
:idprefix:
:idseparator: -
:page-component-title: Application de génération d’une base de données relationnelle à partir d’une ontologie
:page-component-name: OntoRel-App
= {page-component-name}

[#summary]
== Sommaire
*{page-component-name}* génère à partir d'une ontologie et des critères de modélisation, à la fois un ensemble de scripts qui créent une base de données relationnelle (BDR) entièrement fonctionnelle et des graphes de propriétés étiquetés.

SGBDs actuellement pris en charge:

* Relationnel: PostgreSQL
* Graphe: Neo4j & AgensGraph

[#techno]
== Technologies utilisées
L' *{page-component-name}* est développée en Java et utilise Gradle comme outil de construction automatisée
(« build automation tools »).

Les libraires externes suivantes ont été utilisées:

* https://github.com/owlcs/owlapi[OWLAPI]
* https://github.com/snakeyaml/snakeyaml[SnakeYAML]
* https://jgrapht.org[JGraphT]
* https://junit.org[JUnit Jupiter]
* https://www.stringtemplate.org[StringTemplate]

Le fichier exécutable sera dans le répertoire `build/libs`.

=== Entrées

Le logiciel prend en entrée deux fichiers de configuration :

* [nom-de-l'ontologie]-database_config.yaml : contenant les paramètres nécessaires à la création de la base de données relationnelle
* [nom-de-l'ontologie]-ontology_config.yaml : contenant les paramètres nécessaires à la lecture des composants ontologiques

=== Sorties

`{page-component-name}` génère :

* l'ontologie normalisée;
* les scripts de la base de données relationnelle;
* une liste des anomalies trouvées dans l'ontologie;
* un catalogue de mise en correspondance entre des constructeurs ontologiques et les constructeurs relationnels (OntoRelCat).
* le graphe :
** de l'ontologie normalisée (OntoGraph);
** du schéma relationnel (RelGraph);
** du schéma ontologique-relationnel (OntoRelGraph).

=== Utilisation client pour génération des scripts Cypher

Les pré-requis :

* Java 17+
* Neo4j Desktop 2.x ou
* AgensGraph Community Edition v2.x

Les étapes :

. Clônez le dépôt.
. xref:demo/lisezmoi.adoc#demos[Créez vos propres fichiers de configuration] ou réutilisez n'importe quel ensemble de fichiers de configuration présent dans le dossier `/demo`.
. Dans le terminal, depuis le répertoire racine du projet, exécutez la commande suivante : +
----
 java -jar build/libs/ontorela-application-2.3.0-SNAPSHOT.jar generate-cypher <configuration_directory>
----

Suivez xref:demo/lisezmoi.adoc#utilisation[ces étapes] pour exécuter les démonstrations.

== Équipe

Pour plus d'information contacter: +
Christina Khnaisser : Christina.Khnaisser@usherbrooke.ca

Collaborateurs.trices : +
Reine Sonkin Fozi : Reine.Sonkin.Fozi@usherbrooke.ca

Merci à : +
Ameni Souid :  Ameni.Souid@USherbrooke.ca +
Mohamed Amin Gaied :  Mohamed.Amin.Gaied@USherbrooke.ca +
Mouhamad Moustapha Mbaye : Mouhamad.Moustapha.Mbaye@USherbrooke.ca

== Références
Khnaisser, Chantal, Luc Lavoie, Benoit Fraikin, Alan Barton, Sébastien Dussault, Anita Burgun, et Jean-François Ethier. « Using an ontology to derive a sharable and interoperable relational data model for heterogeneous healthcare data and various applications ». In Methods of Information in Medicine, 61(S 02):e73–e88, (Jun 2022). https://doi.org/10.1055/a-1877-9498.

[#licence]
== Copyright et licences

=== Copyright
include::copyright.adoc[]

=== Licences
Le code de ce projet est sous licence
link:liliqr-licence.adoc[LILIQ-R].

La documentation de ce projet est sous licence
https://creativecommons.org/licenses/by/4.0/[CC BY 4.0].
