// Settings
:idprefix:
:idseparator: -
:page-component-title: Application for generating a relational database using an ontology
:page-component-name: Ontorela
= {page-component-name}

[#summary]
== Summary
*{page-component-name}* generates from an ontology and modeling criteria, a set of scripts that create both a fully functional relational database (RDB) and property graphs compatible with Neo4j et AgensGraph.

[#techno]
== Technologies
*{page-component-name}* is developed in Java and uses Gradle as a build automation tool.

The following external libraries were used:
* [OWLAPI](https://github.com/owlcs/owlapi)
* [SnakeYAML](https://github.com/snakeyaml/snakeyaml)
* [JGraphT](https://jgrapht.org)
* [JUnit Jupiter](https://junit.org)
* [StringTemplate](https://www.stringtemplate.org)

The executable file will be in `build/libs`.

=== Inputs

The software takes two configuration files as input:

* [ontology-name]-database_config.yaml: containing parameters for building the relational database
* [ontology-name]-ontology_config.yaml: containing parameters for reading ontological components

=== Outputs

The software generates for an ontology, a set of cypher scripts that construct property graphs compatible with Neo4j and AgensGraph.

=== Usage

Prerequisites:

* Java 17+
* AgensGraph v2.14.1+
* Neo4j v2.1.4

Steps :

. Clone the repository.
. In the terminal run: +
----
 java -jar build/libs/ontorela-application-2.3.0-SNAPSHOT.jar generate-cypher <configuration_directory>
----

== Team members

For more information, please contact: +
Christina Khnaisser : Christina.Khnaisser@usherbrooke.ca

Collaborators : +
Reine Sonkin Fozi : Reine.Sonkin.Fozi@usherbrooke.ca

Thanks to : +
Ameni Souid :  Ameni.Souid@USherbrooke.ca+
Mohamed Amin Gaied :  Mohamed.Amin.Gaied@USherbrooke.ca+
Mouhamad Moustapha Mbaye : Mouhamad.Moustapha.Mbaye@USherbrooke.ca

== Références
Khnaisser, Chantal, Luc Lavoie, Benoit Fraikin, Alan Barton, Sébastien Dussault, Anita Burgun, et Jean-François Ethier. « Using an ontology to derive a sharable and interoperable relational data model for heterogeneous healthcare data and various applications ». In Methods of Information in Medicine, 61(S 02):e73–e88, (Jun 2022). https://doi.org/10.1055/a-1877-9498.

[#licence]
== Copyright and licences

=== Copyright
include::copyright.adoc[]

=== Licences
The code for this project is licensed under the
link:liliqr-licence-english.adoc[English version].

La documentation de ce projet est sous licence
https://creativecommons.org/licenses/by/4.0/[CC BY 4.0].
