owlFilePath: https://raw.githubusercontent.com/OpenLHS/MPHPO/refs/heads/main/MPHPO-full.owl
loadEquivalentClass: false
annotations:
  labels:
    - "http://www.w3.org/2000/01/rdf-schema#label"
    - "http://purl.obolibrary.org/obo/BFO_0000179"
  definitions:
    - "http://purl.org/dc/elements/1.1/description"
    - "http://purl.obolibrary.org/obo/BFO_0000180"
    - "http://purl.obolibrary.org/obo/IAO_0000115"
    - "https://www.w3.org/2000/01/rdf-schema#comment"
